### ISSUE TITLE
FCS_IPSEC_EXT.1.3 modes

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/vpngw#1]
Latest published version of VPN Client Module (v1.1) leaves NDcPP SFR element FCS_IPSEC_EXT.1.3 unmodified, but notes that future versions of the Module will require both transport and tunnel mode to be selected. Should this now be changed to require both modes or should it still be kept the way it currently is?

**Comment by jmcdaniels** [comment]
Removing the app note, leaving both selections.
