### ISSUE TITLE
threat-objective mapping

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/vpngw#3]
Module v1.1 did the threat-objective mapping by listing each objective as the primary key of the table and then mapping associated threats to them. The more typical arrangement (and the default method supported by the schema) is to list the threats as the primary key and then map objectives to those. This conversion switched the mapping around but this created the following issues:
- O.FAIL_SECURE, previously mapped only to Base-PP T.SECURITY_FUNCTIONALITY_FAILURE, now unmapped which will fail ACE_OBJ
- O.TOE_ADMINISTRATION, previously mapped only to Base-PP T.UNAUTHORIZED_ADMINISTRATOR_ACCESS, now unmapped which will fail ACE_OBJ
- O.SYSTEM_MONITORING, previously mapped to T.NETWORK_MISUSE from the Module and T.UNDETECTED_ACTIVITY from the Base-PP - this not a Part 3 failure on its own since it's still mapped, but additional context from the old Module is lost

Discussion will be needed on how best to resolve this.

**Comment by jmcdaniels** [comment]
All are now mapped.
