### ISSUE TITLE
Freeform text in SARs section

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/vpngw#4]
The current schema inserts pre-defined text in the <mod-sars> section and ignores text put into it (though this text does not cause a schema validation error). The SARs text/EA from VPN v1.1 was not able to be ported into Github as a result. The actual text does not meaningfully change how a TOE that conforms to the Module would be evaluated, but if greater consistency with the previous Module version is desired this will need to be addressed.

**Comment by jmcdaniels** [comment]
This should be fine as is.
