### ISSUE TITLE
Extended class in ECD

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/vpngw#5]
The current way that the schema handles ECDs does not have the ability to define a new extended class, only families. In the case of this Module, that would cause a failure of ACE_ECD because the FPF class is a new class and must therefore be defined in the ECD. Alternatively, FPF_RUL_EXT.1 could be re-defined as FDP_RUL_EXT.1 (since it's at least superficially similar to other FDP class SFRs like FDP_IFC/IFF) to avoid needing to make any changes to how the ECD works.

**Comment by jmcdaniels** [comment]
FPF is in the ECD, closing this out.
