### ISSUE TITLE
Double SAR sections

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/vpngw#7]
The current VPNGW Module has two SARs sections: 5.4 and 6.2. Both appear to be getting created automatically by the schema (see #4 ).  The CEM does not mention any need to discuss the SARs in the consistency review - ACE_MCO.1-4 mentions 'the security requirements' in general but the description of the activity only mentions SFRs specifically. Based on this, the 6.2 section is redundant and doesn't appear to be necessary.

**Comment by jmcdaniels** [comment]
Resolved by @kgal.
