### ISSUE TITLE
Error in section A.3 name

### ISSUE THREAD

**Issue by nwherri** [commoncriteria/vpngw#9]
In the Table of Contents - A.3 is titled "Implementation-Based"
Should be "Implementation-Dependent"
This seems to be a recurring problem in newer PPs so the template is wrong. 

A.3.1 titled "Implementation-Based", should be "Implementation-Dependent"
In Table 5 under A.3.1 "Feat-based" but should be "Implementation-Dependent"

**Comment by jmcdaniels** [comment]
Updated.

**Comment by jmcdaniels** [comment]
@kgal can you update template to fix for future PPs?
